class_name MusicDirector
extends Node
## Adaptive music. Four layers of one loop play in sync (calm pad, pulse, tension, danger) and are
## faded in and out by what is happening: vampires nearby, sabotage, the bomb clock, tasks,
## cutscenes. Chases get their own track; level ends and failures get a stinger.
## The music is generated by tools/make_music.py.

const LAYERS := {
	"pad": preload("res://assets/audio/music_pad.wav"),
	"pulse": preload("res://assets/audio/music_pulse.wav"),
	"tension": preload("res://assets/audio/music_tension.wav"),
	"danger": preload("res://assets/audio/music_danger.wav"),
}
const CHASE := preload("res://assets/audio/music_chase.wav")
## The final battle's comic opera, four layers that build with the fight.
const OPERA := {
	"strings": preload("res://assets/audio/music_opera_strings.wav"),
	"choir": preload("res://assets/audio/music_opera_choir.wav"),
	"brass": preload("res://assets/audio/music_opera_brass.wav"),
	"frenzy": preload("res://assets/audio/music_opera_frenzy.wav"),
}
const STING_WIN := preload("res://assets/audio/sting_win.wav")
const STING_FAIL := preload("res://assets/audio/sting_fail.wav")
const BASE_DB := -8.0
const FADE := 1.6 ## volume units per second

var main: Node
var muted := false
var _players := {}
var _level := {} ## current volume 0..1 per layer
var _chase: AudioStreamPlayer
var _chase_level := 0.0
var _sting: AudioStreamPlayer
var _opera := {}
var _opera_level := {}
var _last_state := ""


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	add_to_group("music")
	for key: String in LAYERS:
		var p := AudioStreamPlayer.new()
		p.stream = LAYERS[key]
		p.volume_db = -80.0
		add_child(p)
		_players[key] = p
		_level[key] = 0.0
	_chase = AudioStreamPlayer.new()
	_chase.stream = CHASE
	_chase.volume_db = -80.0
	add_child(_chase)
	for key: String in OPERA:
		var op := AudioStreamPlayer.new()
		op.stream = OPERA[key]
		op.volume_db = -80.0
		add_child(op)
		_opera[key] = op
		_opera_level[key] = 0.0
	_sting = AudioStreamPlayer.new()
	_sting.volume_db = BASE_DB + 2.0
	add_child(_sting)
	for key: String in _players:
		_players[key].play() # all layers start together so they stay in sync


func set_muted(on: bool) -> void:
	muted = on


func _targets() -> Dictionary:
	var t := {"pad": 0.0, "pulse": 0.0, "tension": 0.0, "danger": 0.0, "chase": 0.0}
	if main == null:
		return t
	var state: String = main.state
	var world: World = main.world
	match state:
		"menu":
			t["pad"] = 0.8
			t["pulse"] = 0.35
		"cutscene":
			t["pad"] = 0.7
			var ov: Variant = main._overlay
			if ov is ComicCutscene and ov.kind != "opening":
				t["tension"] = 0.8
		"parkour":
			t["chase"] = 1.0
		"boss":
			pass # the opera plays instead (see _opera_targets)
		"choice":
			t["pad"] = 0.5
			t["tension"] = 1.0
		"levelend":
			t["pad"] = 0.6
		"dead", "ended":
			t["pad"] = 0.25
		_:
			# exploring, a task or a light puzzle
			t["pad"] = 0.85
			t["pulse"] = 0.55 if main.level_idx == 0 else 0.8
			var tension := 0.25 if main.level_idx >= 1 else 0.0
			var danger := 0.0
			var near := _nearest_vampire(world)
			if near < 7.0:
				tension = maxf(tension, clampf((7.0 - near) / 4.0, 0.4, 1.0))
			if not world.sabotage.is_empty():
				tension = 1.0
				if float(world.sabotage["left"]) < 15.0:
					danger = 1.0
			var bomb: float = main.bomb_left
			if bomb < 180.0:
				tension = maxf(tension, 0.8)
			if bomb < 60.0:
				danger = 1.0
			t["tension"] = tension
			t["danger"] = danger
			if state == "task" or state == "playing":
				# keep it quieter while the player concentrates on a task
				for k in ["pad", "pulse", "tension", "danger"]:
					t[k] *= 0.6
	if main.paused:
		for k in t:
			t[k] *= 0.35
	return t


## Distance in tiles to the closest vampire that is still a threat, or a big number.
func _nearest_vampire(world: World) -> float:
	var best := 1e9
	if world == null or world.vampires == null:
		return best
	for i in world.vampires.list.size():
		var v: Dictionary = world.vampires.list[i]
		if not v["alive"] or i == world.vampires.ally_index:
			continue
		best = minf(best, (v["pos"] as Vector2).distance_to(world._foot) / World.TILE)
	return best


const SYNTH := {
	"pad": "res://assets/audio/music_synth_pad.wav",
	"bass": "res://assets/audio/music_synth_bass.wav",
	"drums": "res://assets/audio/music_synth_drums.wav",
	"lead": "res://assets/audio/music_synth_lead.wav",
}
var _synth := {}
var _synth_level := {}


## The 720p edition plays Codex's synthwave layers (street: pad, bass, drums; the Twins: + lead).
func _synth_targets() -> Dictionary:
	var t := {"pad": 0.0, "bass": 0.0, "drums": 0.0, "lead": 0.0}
	var d: Node = main.director if main != null and "director" in main else null
	if d == null or d.act != "720p":
		return t
	t["pad"] = 0.8
	t["bass"] = 0.9 if main.state == "boss" else 0.4
	t["drums"] = 0.9 if main.state == "boss" else 0.0
	if main._overlay is BrawlerGame and main._overlay.stage == "train":
		t["lead"] = 0.85
	if main.paused:
		for k in t:
			t[k] *= 0.35
	return t


## The battle opera: more layers as the fight heats up (BossFight.intensity 0..3).
func _opera_targets() -> Dictionary:
	var t := {"strings": 0.0, "choir": 0.0, "brass": 0.0, "frenzy": 0.0}
	if main == null or main.state != "boss" or main._overlay is BrawlerGame:
		return t
	var level := 0
	if main._overlay is BossFight:
		level = main._overlay.intensity
	t["strings"] = 0.9
	t["choir"] = 0.45 if level == 0 else 0.85
	t["brass"] = 0.9 if level >= 2 else (0.5 if level == 1 else 0.0)
	t["frenzy"] = 0.9 if level >= 3 else 0.0
	if main.paused:
		for k in t:
			t[k] *= 0.35
	return t


func _process(delta: float) -> void:
	var state: String = main.state if main != null else "menu"
	if state != _last_state:
		_on_state(state)
		_last_state = state
	var t := _targets()
	for key: String in _players:
		_level[key] = move_toward(_level[key], t[key], FADE * delta)
		_players[key].volume_db = _db(_level[key])
	var ot := _opera_targets()
	var opera_on := false
	for key: String in _opera:
		_opera_level[key] = move_toward(_opera_level[key], ot[key], FADE * delta)
		_opera[key].volume_db = _db(_opera_level[key])
		opera_on = opera_on or _opera_level[key] > 0.0
	if opera_on and not _opera["strings"].playing:
		for key: String in _opera:
			_opera[key].play() # together, so the layers stay in sync
	elif not opera_on and _opera["strings"].playing:
		for key: String in _opera:
			_opera[key].stop()
	_update_synth(delta)
	_chase_level = move_toward(_chase_level, t["chase"], FADE * 2.0 * delta)
	_chase.volume_db = _db(_chase_level)
	if _chase_level > 0.0 and not _chase.playing:
		_chase.play()
	elif _chase_level <= 0.0 and _chase.playing:
		_chase.stop()
	# the last minute on the bomb: everything a touch faster and higher
	var urgent := main != null and float(main.bomb_left) < 60.0 and state in ["world", "task", "playing"]
	var pitch := 1.06 if urgent else 1.0
	for key: String in _players:
		_players[key].pitch_scale = move_toward(_players[key].pitch_scale, pitch, delta * 0.2)


func _update_synth(delta: float) -> void:
	if _synth.is_empty():
		for key: String in SYNTH:
			if ResourceLoader.exists(SYNTH[key]):
				var p := AudioStreamPlayer.new()
				p.stream = load(SYNTH[key])
				p.volume_db = -80.0
				add_child(p)
				_synth[key] = p
				_synth_level[key] = 0.0
		if _synth.is_empty():
			_synth["none"] = null
			return
	if _synth.has("none"):
		return
	var st := _synth_targets()
	var on := false
	for key: String in _synth:
		_synth_level[key] = move_toward(_synth_level[key], st[key], FADE * delta)
		_synth[key].volume_db = _db(_synth_level[key])
		on = on or _synth_level[key] > 0.0
	var first: AudioStreamPlayer = _synth.values()[0]
	if on and not first.playing:
		for key: String in _synth:
			_synth[key].play()
	elif not on and first.playing:
		for key: String in _synth:
			_synth[key].stop()


func _db(v: float) -> float:
	if muted or v <= 0.001:
		return -80.0
	return BASE_DB + linear_to_db(v)


func _on_state(state: String) -> void:
	if muted:
		return
	if state == "levelend":
		_sting.stream = STING_WIN
		_sting.play()
	elif state == "dead" or (state == "ended" and main != null and float(main.bomb_left) <= 0.0):
		_sting.stream = STING_FAIL
		_sting.play()
