class_name MusicDirector
extends Node
## Adaptive music. Four layers of one loop play in sync (calm pad, pulse, tension, danger) and are
## faded in and out by what is happening: vampires nearby, sabotage, the bomb clock, tasks,
## cutscenes. Chases get their own track; level ends and failures get a stinger.
## The music is generated by tools/make_music.py.

const LAYERS := {
	"pad": preload("res://assets/audio/music_pad.wav"),
	"pulse": preload("res://assets/audio/music_pulse.wav"),
	"tension": preload("res://assets/audio/music_tension.wav"),
	"danger": preload("res://assets/audio/music_danger.wav"),
}
const CHASE := preload("res://assets/audio/music_chase.wav")
const STING_WIN := preload("res://assets/audio/sting_win.wav")
const STING_FAIL := preload("res://assets/audio/sting_fail.wav")
const BASE_DB := -8.0
const FADE := 1.6 ## volume units per second

var main: Node
var muted := false
var _players := {}
var _level := {} ## current volume 0..1 per layer
var _chase: AudioStreamPlayer
var _chase_level := 0.0
var _sting: AudioStreamPlayer
var _last_state := ""


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	add_to_group("music")
	for key: String in LAYERS:
		var p := AudioStreamPlayer.new()
		p.stream = LAYERS[key]
		p.volume_db = -80.0
		add_child(p)
		_players[key] = p
		_level[key] = 0.0
	_chase = AudioStreamPlayer.new()
	_chase.stream = CHASE
	_chase.volume_db = -80.0
	add_child(_chase)
	_sting = AudioStreamPlayer.new()
	_sting.volume_db = BASE_DB + 2.0
	add_child(_sting)
	for key: String in _players:
		_players[key].play() # all layers start together so they stay in sync


func set_muted(on: bool) -> void:
	muted = on


func _targets() -> Dictionary:
	var t := {"pad": 0.0, "pulse": 0.0, "tension": 0.0, "danger": 0.0, "chase": 0.0}
	if main == null:
		return t
	var state: String = main.state
	var world: World = main.world
	match state:
		"menu":
			t["pad"] = 0.8
			t["pulse"] = 0.35
		"cutscene":
			t["pad"] = 0.7
			var ov: Variant = main._overlay
			if ov is ComicCutscene and ov.kind != "opening":
				t["tension"] = 0.8
		"parkour":
			t["chase"] = 1.0
		"choice":
			t["pad"] = 0.5
			t["tension"] = 1.0
		"levelend":
			t["pad"] = 0.6
		"dead", "ended":
			t["pad"] = 0.25
		_:
			# exploring, a task or a light puzzle
			t["pad"] = 0.85
			t["pulse"] = 0.55 if main.level_idx == 0 else 0.8
			var tension := 0.25 if main.level_idx >= 1 else 0.0
			var danger := 0.0
			var near := _nearest_vampire(world)
			if near < 7.0:
				tension = maxf(tension, clampf((7.0 - near) / 4.0, 0.4, 1.0))
			if not world.sabotage.is_empty():
				tension = 1.0
				if float(world.sabotage["left"]) < 15.0:
					danger = 1.0
			var bomb: float = main.bomb_left
			if bomb < 180.0:
				tension = maxf(tension, 0.8)
			if bomb < 60.0:
				danger = 1.0
			t["tension"] = tension
			t["danger"] = danger
			if state == "task" or state == "playing":
				# keep it quieter while the player concentrates on a task
				for k in ["pad", "pulse", "tension", "danger"]:
					t[k] *= 0.6
	if main.paused:
		for k in t:
			t[k] *= 0.35
	return t


## Distance in tiles to the closest vampire that is still a threat, or a big number.
func _nearest_vampire(world: World) -> float:
	var best := 1e9
	if world == null or world.vampires == null:
		return best
	for i in world.vampires.list.size():
		var v: Dictionary = world.vampires.list[i]
		if not v["alive"] or i == world.vampires.ally_index:
			continue
		best = minf(best, (v["pos"] as Vector2).distance_to(world._foot) / World.TILE)
	return best


func _process(delta: float) -> void:
	var state: String = main.state if main != null else "menu"
	if state != _last_state:
		_on_state(state)
		_last_state = state
	var t := _targets()
	for key: String in _players:
		_level[key] = move_toward(_level[key], t[key], FADE * delta)
		_players[key].volume_db = _db(_level[key])
	_chase_level = move_toward(_chase_level, t["chase"], FADE * 2.0 * delta)
	_chase.volume_db = _db(_chase_level)
	if _chase_level > 0.0 and not _chase.playing:
		_chase.play()
	elif _chase_level <= 0.0 and _chase.playing:
		_chase.stop()
	# the last minute on the bomb: everything a touch faster and higher
	var urgent := main != null and float(main.bomb_left) < 60.0 and state in ["world", "task", "playing"]
	var pitch := 1.06 if urgent else 1.0
	for key: String in _players:
		_players[key].pitch_scale = move_toward(_players[key].pitch_scale, pitch, delta * 0.2)


func _db(v: float) -> float:
	if muted or v <= 0.001:
		return -80.0
	return BASE_DB + linear_to_db(v)


func _on_state(state: String) -> void:
	if muted:
		return
	if state == "levelend":
		_sting.stream = STING_WIN
		_sting.play()
	elif state == "dead" or (state == "ended" and main != null and float(main.bomb_left) <= 0.0):
		_sting.stream = STING_FAIL
		_sting.play()
